Performance-optimized Circle Tool
mbrlabs/Lorien pull request #120
Opened 2022-05-16 16:20 UTC by Hiderrr

The template I used to write the CircleTool.gd class was the RecangleTool.gd class.
Because of this, the code is written in a similar way. I hope it helps (;

**Features:**
  - Well-looking, though not expansive circles (empty, outlines only)
  - UI tool toggle control (created in the same manner as other tools')
  - Number of points on the circle is configurable through CircleTool.gd class
  - While the circle remains in motion (user hasn't released LMB yet), the circle is drawn using a far limited number of points, in order to increase performance (which also gives quite a good looking effect of a "polygonized-circle")
  - Once settled, the final number of points is set and saved

One last thing to do, to make the tool release-ready, is to create a shortcut (C) for the tool

**Future plans:**
  - If I am requested to, I'd more than happily try to implement these features:
    - Changing color of selected strokes to the chosen one
    - UI for the Circle tool, giving additional the user additional control over the number of circle's points in *motion* and *settled* states
    - Making an eraser tool, that actually erases points ((:
    
Regards!
Hiderr

2022-05-17 14:04 UTC, mbrlabs requested changes
Very nice implementation, thanks! I left some comments.
Also in the title you mentioned something about the shift key, but it doen't seem to do anything?

As for the shorcut: `c` is currently used to center the canvas to the mouse position. I think it's best to change that to the `space` key and use `c` for the circle tool (see Project settings > Input map).

2022-05-17 14:12 UTC, mbrlabs commented
> Changing color of selected strokes to the chosen one

I think that's already possible, no?

> UI for the Circle tool, giving additional the user additional control over the number of circle's points in motion and settled states

I think it's fine as is. What could be added though is drawing ellipses instead of circles when the shift key is held

> Making an eraser tool, that actually erases points 

That would be great! See this issue for inspiration: https://github.com/mbrlabs/Lorien/issues/74. Basically when the eraser intersects with a bursh it would delete it. If you want to discuss this further let's talk about it in the linked issue

2022-05-20 16:48 UTC, Hiderrr commented on lorien/InfiniteCanvas/Tools/CircleTool.gd
> +		cos_arr[i] = cos(deg2rad(i))
I meant that the tool behaves similarly, as if you hold shift in gimp (:

Thanks for the informative review, I'll commit the requested changes today.

2022-05-20 17:40 UTC, Hiderrr commented on lorien/InfiniteCanvas/Tools/CircleTool.gd
> +		cos_arr[i] = cos(deg2rad(i))
Also a note here: for loop cannot be simplified, as it uses the step passed to the function for limiting the number of points on the circle.

2022-05-20 17:47 UTC, mbrlabs commented on lorien/InfiniteCanvas/Tools/CircleTool.gd
> +		cos_arr[i] = cos(deg2rad(i))
I just meant the loop in the constructor (which increments in 1-steps).

2022-05-20 18:02 UTC, mbrlabs approved these changes

2022-05-20 18:07 UTC, mbrlabs commented
Code looks good! Also thanks for the ellipse tool. 👍 
I just played around with it a bit and i think it's better to make the ellipse default and enable the circle when holding the shift key. This is because most of the time you want to encircle something and it's easier to do that with an ellipse.

2022-05-20 18:12 UTC, Hiderrr commented
> I just played around with it a bit and i think it's better to make the ellipse default and enable the circle when holding the shift key

I do agree, that's actually default behavior in almost all software.

2022-05-20 18:37 UTC, Hiderrr commented
I combined the commits to make the tree a little cleaner.
Last commit alters the behavior of SHIFT, so that now it enables "circle mode", and the default mode is "ellipse mode"

2022-05-20 18:47 UTC, mbrlabs commented
Great work, thank you very much! :)

2022-05-20 18:47 UTC, merged